name: madshop_ui_zhirnoff
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/tabbar_items/
  
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
    
    - family: Raleway-Regualar
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 500

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Light.ttf
          weight: 300

    - family: NunitoSans-400
      fonts:
        - asset: assets/fonts/NunitoSans-Light.ttf
          weight: 400